site_name: nelsone.io
theme:
  features:
    - navigation.tabs
    - toc.integrate
    - navigation.top
    - navigation.instant
nav:
  - Home: "index.md"
  - Landing Zone:
    - Getting Started: "landing_zone/index.md"
